version: '3'

services:

    reverse-proxy:
        image: nginx:latest
        container_name: reverse_proxy
        depends_on:
            - fortune-tent
            - fortune-cookie
            - fortune-teller
        volumes:
            - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80

    fortune-tent:
        image: fortune-tent
        container_name: fortune-tent
        build:
            context: ./fortune-tent
        depends_on:
            - fortune-cookie
            - fortune-teller
        ports:
            - 8080:80
        restart: on-failure

    fortune-cookie:
        image: fortune-cookie
        container_name: fortune-cookie
        build:
            context: ./fortune-cookie
        ports:
            - 5001:5001
        restart: on-failure

    fortune-teller:
        image: fortune-teller
        container_name: fortune-teller
        build:
            context: ./fortune-teller
        ports:
            - 5002:5002
        restart: on-failure